### ISSUE TITLE
Problem with c++ implementation.

### ISSUE THREAD

**Issue by mohit-madan** [cost2100/cost2100#4]
I am not able to run the c++ code due to some missing header files required in the code like "port.h", "debug.h", etc. Are there any missing files or I am doing some mistake. I am just trying to compile the c++ code with it++ installed on my machine.

**Comment by mohit-madan** [comment]
I found those files in the html files.

**Comment by mohit-madan** [comment]
> I am not able to run the c++ code due to some missing header files required in the code like "port.h", "debug.h", etc. Are there any missing files or I am doing some mistake. I am just trying to compile the c++ code with it++ installed on my machine.

Actually, I found those files embedded within the html files

**Comment by ImportMengjie** [comment]
@mohit-madan The HTML files only have the header files, not cpp files. 

How to solve that?

thanks!!!

**Comment by mohit-madan** [comment]
the only cpp files are the ones in cost2100/cost2100 main directory
